name: worktime
description: "Worktime Flutter Web UI prototype with mock data."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  go_router: ^17.3.0
  http: ^1.2.2
  intl: 0.20.2
  shadcn_ui: ^0.55.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  build_runner: ^2.5.4
  widgetbook: ^3.25.0
  widgetbook_annotation: ^3.11.0
  widgetbook_generator: ^3.14.0

flutter:
  uses-material-design: true
